TriggerMode: 0
TriggerSource: 0
SystemTime: false

DriverMode: 0 # 0: 常规驱动模式, 1: 对焦模式, 2: 调焦模式

camera0:
  image_width: 1920
  image_height: 1200

  auto_exposure: true
  exposure_time: 200000.0
  exposure_lower: 20.0

  auto_gain: false
  gain: 1.0

  fps: 10.0
  brightness: 75.0

camera1:
  image_width: 1920
  image_height: 1200

  auto_exposure: true
  exposure_time: 200000.0
  exposure_lower: 20.0

  auto_gain: false
  gain: 1.0

  fps: 10.0
  brightness: 75.0